### PR TITLE
Fix concurrent-to field in WARC headers

### PR DESCRIPTION
**Pull request by BubuAnabelas**
What's missing is assigning the Warcinfo-ID field correctly and finding the last one (if there is one) when appending to a WARC file

### CODE REVIEW

**Comment by N0taN3rd** [comment]
@BubuAnabelas ok I gave the changes from your PR a test run (merged into dev branch) and used  [Squidwarc](https://github.com/N0taN3rd/Squidwarc) to generate a WARC file which was then replayed using [Pywb](https://github.com/webrecorder/pywb).
Squidwarc depends directly on node-warc for the WARC generation and is high fidelity archival crawler I have written.

Your changes appear to introduce additional **CRLF**s which causes the **length** of the  WARC records to be off as well as the **length** of the response bodies. 
See annotated image below   comparing your changes _PR #5_ merged into the dev branch vs the dev branch as it it now. 
diff

If you could switch the branch your  PR  is based on (from master to dev) and work from their to ensure that no additional **CRLF** are introduced (see [RFC 7230](https://tools.ietf.org/html/rfc7230) for CRLFs in HTTP).
I believe we can get the **CRLF** issue resolved without to much headache.
I highly recommend using [WAIL](https://github.com/N0taN3rd/wail/releases)  for managing the replay of the WARCs generated. It will do the setup for you automatically.
Otherwise Pywb is the _de facto_ replay  system and is easy to use to test it out.

**Comment by BubuAnabelas** [comment]
I added some unnecesary CRLF by mistake in the request and response block headers. In the next commit I'll solve this and the current file conflicts from switching branch

**Comment by BubuAnabelas** [comment]
Bumping this since it's ready for merging.

**Comment by N0taN3rd** [comment]
@BubuAnabelas gave it a test run and everything works perfectly.
Again sincerest apologies for the delay in my responses and time it took to get this merged.

Love the refactoring of warcFields.js to use template literals.
Merging into dev then strait into master!

Thank you for this!!!!

**Pull request merged**
